# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py310"

select = [
    "ALL",
]

# All the ones without a comment were the ones that are currently violated
# by the codebase. The plan is to fix them all (when sensible) and then enable them.
ignore = [
    "ANN",
    "ARG",
    "B905",
    "D102",
    "D103",
    "D202", # No blank lines allowed after function docstring
    "D203", # 1 blank line required before class docstring
    "D205",
    "D213", # Multi-line docstring summary should start at the second line
    "D401",
    "D404", # First word of the docstring should not be This
    "D406", # Section name should end with a newline
    "D407", # Section name underlining
    "D411", # Missing blank line before section
    "E501", # line too long
    "E731", # do not assign a lambda expression, use a def
    "EXE002",
    "FBT",
    "FIX004",
    "ISC001",
    "N806",
    "N818",
    "PD901",
    "PERF203",
    "PERF401",
    "PLR",
    "PLW2901",
    "RET505",
    "RUF006",
    "S101",
    "SLF001",
    "TRY004",
]

[per-file-ignores]
"tests/*.py" = ["ALL"]
".github/*py" = ["INP001"]
"test_dependencies.py" = ["ALL"]

[flake8-pytest-style]
fixture-parentheses = false

[pyupgrade]
keep-runtime-typing = true

[mccabe]
max-complexity = 25
