# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py310"

select = ["ALL"]

# All the ones without a comment were the ones that are currently violated
# by the codebase. The plan is to fix them all (when sensible) and then enable them.
ignore = [
    "ANN",
    "ANN101",  # Missing type annotation for {name} in method
    "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed in {name}
    "D202",    # No blank lines allowed after function docstring
    "D203",    # 1 blank line required before class docstring
    "D213",    # Multi-line docstring summary should start at the second line
    "D401",    # First line of docstring should be in imperative mood
    "D402",    # First line should not be the function's signature
    "D404",    # First word of the docstring should not be This
    "D406",    # Section name should end with a newline
    "D407",    # Section name underlining
    "D411",    # Missing blank line before section
    "E501",    # line too long
    "E731",    # do not assign a lambda expression, use a def
    "FIX002",  # Line contains TODO"
    "FIX004",  # Line contains HACK, consider resolving the issue
    "FBT001",  # Boolean positional arg in function definition
    "FBT002",  # Boolean default value in function definition
    "PD901",   # df is a bad variable name. Be kinder to your future self.
    "PERF203",
    "PERF401",
    "PLR",
    "PLR0913", # Too many arguments to function call (N > 5)
    "PLW0603", # Using the global statement to update `X` is discouraged
    "PLW2901",
    "RET505",
    "RUF006",
    "S101",    # Use of assert detected
    "S603",    # `subprocess` call: check for execution of untrusted input
    "S607",    # Starting a process with a partial executable path
    "SLF001",  # Private member accessed
    "SLF001",  # Private member accessed
    "T20",     # flake8-print
    "TD002",   # Missing author in TODO; try: `# TODO(<author_name>): ...`
    "TD003",   # Missing issue link on the line following this TODO
]

[per-file-ignores]
"tests/*.py" = ["ALL"]
".github/*py" = ["INP001"]
"test_dependencies.py" = ["ALL"]

[flake8-pytest-style]
fixture-parentheses = false

[pyupgrade]
keep-runtime-typing = true

[mccabe]
max-complexity = 25
