#!/usr/bin/env bash
set -ex
cd "$(dirname "$0")/.."

if grep -q 'mypy-dev==1.14.0a3' core/requirements_test.txt; then
    # mypy-dev==1.14.0a3 seems to not be available anymore, HA 2024.12 is affected
    sed -i 's/mypy-dev==1.14.0a3/mypy-dev==1.14.0a7/' core/requirements_test.txt
fi

uv pip install -r core/requirements.txt
uv pip install -r core/requirements_test.txt
uv pip install -e core/
uv pip install ulid-transform # this is in Adaptive-lighting's manifest.json
uv pip install $(python test_dependencies.py)
