#!/usr/bin/env bash
set -ex

# Link custom components
ln -fs /app/custom_components/adaptive_lighting /core/homeassistant/components/adaptive_lighting

# Link tests
ln -fs /app/tests /core/tests/components/adaptive_lighting
