#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."

# Clone only if the folder doesn't exist
if [[ ! -d "core" ]]; then
    git clone --depth 1 --branch dev https://github.com/home-assistant/core.git
fi

./scripts/install_ha
pre-commit install-hooks
