#!/usr/bin/env bash
set -ex
cd "$(dirname "$0")/.."

# Clone only if the folder doesn't exist
if [[ ! -d "core" ]]; then
    git clone --depth 1 --branch dev https://github.com/home-assistant/core.git
fi

pip install \
    colorlog \
    pip \
    ruff \
    uv

pip cache purge

uv venv --clear --python 3.13
./scripts/setup-dependencies
./scripts/setup-symlinks
uv run pre-commit install-hooks
