name: Install Dependencies

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Check out code from GitHub
        uses: actions/checkout@v4
        with:
          repository: home-assistant/core
          path: core
      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          echo "::warning::### WARNING! Deprecation warnings muted with option '--use-pep517' please address this at some point in pytest.yaml. ###"
          pip install -r core/requirements.txt --use-pep517
          pip install -r core/requirements_test.txt --use-pep517
          pip install -e core/ --use-pep517
          pip install $(python test_dependencies.py) --use-pep517
